#lutz
version: "3"
services: 
  db:
    image: postgres:alpine
    restart: always
    container_name: postgres_docker
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      # POSTGRES_DB: proffy
    ports:
         - 3333:8080/tcp

    networks:
      - postgres-compose-network
  
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "proffy@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "proffy"
  #   ports:
  #     - "5432:5432"
  #   depends_on:
  #     - db
  #   networks:
  #     - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  db-data:
    driver: local
